In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('data/cleaned_ecommerce_data.csv')
df.head()

,order_id,customer_name,age,gender,city,order_date,product_name,category,unit_price,quantity,email,payment_method,status
0,ORD-10537,Maham Raza,60.0,Male,Islamabad,2025-02-06,Headphones,Accessories,9238.84,1,maham.raza29@gmail.com,EasyPaisa,Pending
1,ORD-10016,Maham Sheikh,34.0,Female,Sialkot,2024-06-18,Smart Watch,Accessories,11754.36,4,maham.sheikh17@gmail.com,Bank Transfer,Pending
2,ORD-10620,Hamza Sheikh,18.0,Female,Multan,2025-08-11,Monitor,Electronics,44713.92,3,hamza.sheikh90@gmail.com,EasyPaisa,Returned
3,ORD-10254,Ahmed Ahmed,56.0,Male,Multan,2025-05-22,Keyboard,Accessories,4363.75,2,ahmed.ahmed33@gmail.com,Cash,Pending
4,ORD-10527,Hina Butt,37.0,Male,Rawalpindi,2024-01-25,Monitor,Electronics,41632.93,2,hina.butt42@gmail.com,Bank Transfer,Returned

In [3]:
# creating a new column using existing columns
# as, total_price = quantity * unit_price
df['total_price'] = df['quantity'] * df['unit_price']
df.head()

,order_id,customer_name,age,gender,city,order_date,product_name,category,unit_price,quantity,email,payment_method,status,total_price
0,ORD-10537,Maham Raza,60.0,Male,Islamabad,2025-02-06,Headphones,Accessories,9238.84,1,maham.raza29@gmail.com,EasyPaisa,Pending,9238.84
1,ORD-10016,Maham Sheikh,34.0,Female,Sialkot,2024-06-18,Smart Watch,Accessories,11754.36,4,maham.sheikh17@gmail.com,Bank Transfer,Pending,47017.44
2,ORD-10620,Hamza Sheikh,18.0,Female,Multan,2025-08-11,Monitor,Electronics,44713.92,3,hamza.sheikh90@gmail.com,EasyPaisa,Returned,134141.76
3,ORD-10254,Ahmed Ahmed,56.0,Male,Multan,2025-05-22,Keyboard,Accessories,4363.75,2,ahmed.ahmed33@gmail.com,Cash,Pending,8727.50
4,ORD-10527,Hina Butt,37.0,Male,Rawalpindi,2024-01-25,Monitor,Electronics,41632.93,2,hina.butt42@gmail.com,Bank Transfer,Returned,83265.86

In [4]:
# Vectorized Operations
df['unit_price'] = df['unit_price'] * 2
df.head()

,order_id,customer_name,age,gender,city,order_date,product_name,category,unit_price,quantity,email,payment_method,status,total_price
0,ORD-10537,Maham Raza,60.0,Male,Islamabad,2025-02-06,Headphones,Accessories,18477.68,1,maham.raza29@gmail.com,EasyPaisa,Pending,9238.84
1,ORD-10016,Maham Sheikh,34.0,Female,Sialkot,2024-06-18,Smart Watch,Accessories,23508.72,4,maham.sheikh17@gmail.com,Bank Transfer,Pending,47017.44
2,ORD-10620,Hamza Sheikh,18.0,Female,Multan,2025-08-11,Monitor,Electronics,89427.84,3,hamza.sheikh90@gmail.com,EasyPaisa,Returned,134141.76
3,ORD-10254,Ahmed Ahmed,56.0,Male,Multan,2025-05-22,Keyboard,Accessories,8727.50,2,ahmed.ahmed33@gmail.com,Cash,Pending,8727.50
4,ORD-10527,Hina Butt,37.0,Male,Rawalpindi,2024-01-25,Monitor,Electronics,83265.86,2,hina.butt42@gmail.com,Bank Transfer,Returned,83265.86

### apply() Function
- apply() is used when you need to run a custom function row-wise or column-wise. Unlike vectorized df['col'] * 2, apply() is for logic/if-else
- apply() is used a lot for feature engineering
- But apply() is slower

In [5]:
# Example 1: apply() on a column - Create price category
# First define the custom fuction which you want to apply()
def price_category(price: float) -> float:
    if price > 60000:
        return "Expensive" # always use return statement for apply()
    elif price > 20000:
        return "Mid"
    else: 
        return "Cheap"

# Now, Creating new column and implementing apply()
df['price_level'] = df['unit_price'].apply(price_category)
df.head()

,order_id,customer_name,age,gender,city,order_date,product_name,category,unit_price,quantity,email,payment_method,status,total_price,price_level
0,ORD-10537,Maham Raza,60.0,Male,Islamabad,2025-02-06,Headphones,Accessories,18477.68,1,maham.raza29@gmail.com,EasyPaisa,Pending,9238.84,Cheap
1,ORD-10016,Maham Sheikh,34.0,Female,Sialkot,2024-06-18,Smart Watch,Accessories,23508.72,4,maham.sheikh17@gmail.com,Bank Transfer,Pending,47017.44,Mid
2,ORD-10620,Hamza Sheikh,18.0,Female,Multan,2025-08-11,Monitor,Electronics,89427.84,3,hamza.sheikh90@gmail.com,EasyPaisa,Returned,134141.76,Expensive
3,ORD-10254,Ahmed Ahmed,56.0,Male,Multan,2025-05-22,Keyboard,Accessories,8727.50,2,ahmed.ahmed33@gmail.com,Cash,Pending,8727.50,Cheap
4,ORD-10527,Hina Butt,37.0,Male,Rawalpindi,2024-01-25,Monitor,Electronics,83265.86,2,hina.butt42@gmail.com,Bank Transfer,Returned,83265.86,Expensive

In [6]:
# Example 2: apply() with lambda on a column - Extract email domain
df['email_domain'] = df['email'].apply(lambda x: x.split('@')[1] if isinstance(x,str) and '@' in x else None)
df.head()

,order_id,customer_name,age,gender,city,order_date,product_name,category,unit_price,quantity,email,payment_method,status,total_price,price_level,email_domain
0,ORD-10537,Maham Raza,60.0,Male,Islamabad,2025-02-06,Headphones,Accessories,18477.68,1,maham.raza29@gmail.com,EasyPaisa,Pending,9238.84,Cheap,gmail.com
1,ORD-10016,Maham Sheikh,34.0,Female,Sialkot,2024-06-18,Smart Watch,Accessories,23508.72,4,maham.sheikh17@gmail.com,Bank Transfer,Pending,47017.44,Mid,gmail.com
2,ORD-10620,Hamza Sheikh,18.0,Female,Multan,2025-08-11,Monitor,Electronics,89427.84,3,hamza.sheikh90@gmail.com,EasyPaisa,Returned,134141.76,Expensive,gmail.com
3,ORD-10254,Ahmed Ahmed,56.0,Male,Multan,2025-05-22,Keyboard,Accessories,8727.50,2,ahmed.ahmed33@gmail.com,Cash,Pending,8727.50,Cheap,gmail.com
4,ORD-10527,Hina Butt,37.0,Male,Rawalpindi,2024-01-25,Monitor,Electronics,83265.86,2,hina.butt42@gmail.com,Bank Transfer,Returned,83265.86,Expensive,gmail.com

In [7]:
# Example 3: apply() on Rows - axis=1 _Create discount based on multiple columns
def calc_discount(row):
    if row['status'] == 'Pending' and row['payment_method'] == 'Bank Transfer':
        return row['total_price'] * 0.10 # 10% discount
    else:
        return 0
df['discount'] = df.apply(calc_discount, axis=1) # axis=1 means row-wise, by default axis=0 that is column-wise which means one value at a time
df.head()

,order_id,customer_name,age,gender,city,order_date,product_name,category,unit_price,quantity,email,payment_method,status,total_price,price_level,email_domain,discount
0,ORD-10537,Maham Raza,60.0,Male,Islamabad,2025-02-06,Headphones,Accessories,18477.68,1,maham.raza29@gmail.com,EasyPaisa,Pending,9238.84,Cheap,gmail.com,0.000
1,ORD-10016,Maham Sheikh,34.0,Female,Sialkot,2024-06-18,Smart Watch,Accessories,23508.72,4,maham.sheikh17@gmail.com,Bank Transfer,Pending,47017.44,Mid,gmail.com,4701.744
2,ORD-10620,Hamza Sheikh,18.0,Female,Multan,2025-08-11,Monitor,Electronics,89427.84,3,hamza.sheikh90@gmail.com,EasyPaisa,Returned,134141.76,Expensive,gmail.com,0.000
3,ORD-10254,Ahmed Ahmed,56.0,Male,Multan,2025-05-22,Keyboard,Accessories,8727.50,2,ahmed.ahmed33@gmail.com,Cash,Pending,8727.50,Cheap,gmail.com,0.000
4,ORD-10527,Hina Butt,37.0,Male,Rawalpindi,2024-01-25,Monitor,Electronics,83265.86,2,hina.butt42@gmail.com,Bank Transfer,Returned,83265.86,Expensive,gmail.com,0.000

### .map() Function
- map() in pandas = "dictionary look-up for 1 column"
- It's used when we want to replace/transform each value in a single column using a distionary, function, or Series

In [8]:
city_codes = {'Islamabad' : "ISL", 'Sialkot' : 'SKT', 'Multan' : 'MUL', 'Rawalpindi' : 'RWL', 'Karachi' : "KAR"}
df['city_code'] = df['city'].map(city_codes)
df.head()

,order_id,customer_name,age,gender,city,order_date,product_name,category,unit_price,quantity,email,payment_method,status,total_price,price_level,email_domain,discount,city_code
0,ORD-10537,Maham Raza,60.0,Male,Islamabad,2025-02-06,Headphones,Accessories,18477.68,1,maham.raza29@gmail.com,EasyPaisa,Pending,9238.84,Cheap,gmail.com,0.000,ISL
1,ORD-10016,Maham Sheikh,34.0,Female,Sialkot,2024-06-18,Smart Watch,Accessories,23508.72,4,maham.sheikh17@gmail.com,Bank Transfer,Pending,47017.44,Mid,gmail.com,4701.744,SKT
2,ORD-10620,Hamza Sheikh,18.0,Female,Multan,2025-08-11,Monitor,Electronics,89427.84,3,hamza.sheikh90@gmail.com,EasyPaisa,Returned,134141.76,Expensive,gmail.com,0.000,MUL
3,ORD-10254,Ahmed Ahmed,56.0,Male,Multan,2025-05-22,Keyboard,Accessories,8727.50,2,ahmed.ahmed33@gmail.com,Cash,Pending,8727.50,Cheap,gmail.com,0.000,MUL
4,ORD-10527,Hina Butt,37.0,Male,Rawalpindi,2024-01-25,Monitor,Electronics,83265.86,2,hina.butt42@gmail.com,Bank Transfer,Returned,83265.86,Expensive,gmail.com,0.000,RWL

### np.where()

In [10]:
# we can also np.where()
df['bulk_order'] = np.where(df['quantity'] >= 3, 'Bulk', 'Small')
df.head()

,order_id,customer_name,age,gender,city,order_date,product_name,category,unit_price,quantity,email,payment_method,status,total_price,price_level,email_domain,discount,city_code,bulk_order
0,ORD-10537,Maham Raza,60.0,Male,Islamabad,2025-02-06,Headphones,Accessories,18477.68,1,maham.raza29@gmail.com,EasyPaisa,Pending,9238.84,Cheap,gmail.com,0.000,ISL,Small
1,ORD-10016,Maham Sheikh,34.0,Female,Sialkot,2024-06-18,Smart Watch,Accessories,23508.72,4,maham.sheikh17@gmail.com,Bank Transfer,Pending,47017.44,Mid,gmail.com,4701.744,SKT,Bulk
2,ORD-10620,Hamza Sheikh,18.0,Female,Multan,2025-08-11,Monitor,Electronics,89427.84,3,hamza.sheikh90@gmail.com,EasyPaisa,Returned,134141.76,Expensive,gmail.com,0.000,MUL,Bulk
3,ORD-10254,Ahmed Ahmed,56.0,Male,Multan,2025-05-22,Keyboard,Accessories,8727.50,2,ahmed.ahmed33@gmail.com,Cash,Pending,8727.50,Cheap,gmail.com,0.000,MUL,Small
4,ORD-10527,Hina Butt,37.0,Male,Rawalpindi,2024-01-25,Monitor,Electronics,83265.86,2,hina.butt42@gmail.com,Bank Transfer,Returned,83265.86,Expensive,gmail.com,0.000,RWL,Small

### np.select()
- "Multiple if-elif-else in 1 line" for pandas columns
- map() is for 1-to-1 dictionary. np.select() is for when you have conditions
- Syntax:
np.select(condition list, choice list, default)

In [11]:
conditions = [
    df['unit_price'] > 50000,
    df['unit_price'] > 20000,
    df['unit_price'] > 5000,
    df['unit_price'] <= 5000
]

choices = [
    'Premium',
    'High',
    'Mid',
    'Budget'
]

df['price_tier'] = np.select(conditions, choices, default='Unknown')
df.head()

,order_id,customer_name,age,gender,city,order_date,product_name,category,unit_price,quantity,email,payment_method,status,total_price,price_level,email_domain,discount,city_code,bulk_order,price_tier
0,ORD-10537,Maham Raza,60.0,Male,Islamabad,2025-02-06,Headphones,Accessories,18477.68,1,maham.raza29@gmail.com,EasyPaisa,Pending,9238.84,Cheap,gmail.com,0.000,ISL,Small,Mid
1,ORD-10016,Maham Sheikh,34.0,Female,Sialkot,2024-06-18,Smart Watch,Accessories,23508.72,4,maham.sheikh17@gmail.com,Bank Transfer,Pending,47017.44,Mid,gmail.com,4701.744,SKT,Bulk,High
2,ORD-10620,Hamza Sheikh,18.0,Female,Multan,2025-08-11,Monitor,Electronics,89427.84,3,hamza.sheikh90@gmail.com,EasyPaisa,Returned,134141.76,Expensive,gmail.com,0.000,MUL,Bulk,Premium
3,ORD-10254,Ahmed Ahmed,56.0,Male,Multan,2025-05-22,Keyboard,Accessories,8727.50,2,ahmed.ahmed33@gmail.com,Cash,Pending,8727.50,Cheap,gmail.com,0.000,MUL,Small,Mid
4,ORD-10527,Hina Butt,37.0,Male,Rawalpindi,2024-01-25,Monitor,Electronics,83265.86,2,hina.butt42@gmail.com,Bank Transfer,Returned,83265.86,Expensive,gmail.com,0.000,RWL,Small,Premium

### NOTE:

| Need           |  Use        |
|----------------|--------------
|Dict replacement|  map()      |
|2 conditions    |  np.where() |
|3+ conditions   | np.select() |